apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-client-http-redirect-cm
  namespace: test-b
  labels:
    app: *app-name
data:
  PORT: "3000"
  POD_NAME: "pod client-http-redirect (ns test-b)"
  API_VERSION: "version 1"
  POD_PATH: ""
  JWTKEY: "my_secret_key"
  HOST: "dns:///svc-go-grpc-service-server:50051"