// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package balance

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN         HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING         HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING     HealthCheckResponse_ServingStatus = 2
	HealthCheckResponse_SERVICE_UNKNOWN HealthCheckResponse_ServingStatus = 3
)

var HealthCheckResponse_ServingStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "SERVING",
	2: "NOT_SERVING",
	3: "SERVICE_UNKNOWN",
}

var HealthCheckResponse_ServingStatus_value = map[string]int32{
	"UNKNOWN":         0,
	"SERVING":         1,
	"NOT_SERVING":     2,
	"SERVICE_UNKNOWN": 3,
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return proto.EnumName(HealthCheckResponse_ServingStatus_name, int32(x))
}

func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{11, 0}
}

type Balance struct {
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Account              string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Amount               int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	DateBalance          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=date_balance,json=dateBalance,proto3" json:"date_balance,omitempty"`
	Description          string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Balance) Reset()         { *m = Balance{} }
func (m *Balance) String() string { return proto.CompactTextString(m) }
func (*Balance) ProtoMessage()    {}
func (*Balance) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Balance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Balance.Unmarshal(m, b)
}
func (m *Balance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Balance.Marshal(b, m, deterministic)
}
func (m *Balance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Balance.Merge(m, src)
}
func (m *Balance) XXX_Size() int {
	return xxx_messageInfo_Balance.Size(m)
}
func (m *Balance) XXX_DiscardUnknown() {
	xxx_messageInfo_Balance.DiscardUnknown(m)
}

var xxx_messageInfo_Balance proto.InternalMessageInfo

func (m *Balance) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Balance) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *Balance) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Balance) GetDateBalance() *timestamppb.Timestamp {
	if m != nil {
		return m.DateBalance
	}
	return nil
}

func (m *Balance) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type AddBalanceRequest struct {
	Balance              *Balance `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBalanceRequest) Reset()         { *m = AddBalanceRequest{} }
func (m *AddBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*AddBalanceRequest) ProtoMessage()    {}
func (*AddBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *AddBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBalanceRequest.Unmarshal(m, b)
}
func (m *AddBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBalanceRequest.Marshal(b, m, deterministic)
}
func (m *AddBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBalanceRequest.Merge(m, src)
}
func (m *AddBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_AddBalanceRequest.Size(m)
}
func (m *AddBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddBalanceRequest proto.InternalMessageInfo

func (m *AddBalanceRequest) GetBalance() *Balance {
	if m != nil {
		return m.Balance
	}
	return nil
}

type AddBalanceResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBalanceResponse) Reset()         { *m = AddBalanceResponse{} }
func (m *AddBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*AddBalanceResponse) ProtoMessage()    {}
func (*AddBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *AddBalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBalanceResponse.Unmarshal(m, b)
}
func (m *AddBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBalanceResponse.Marshal(b, m, deterministic)
}
func (m *AddBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBalanceResponse.Merge(m, src)
}
func (m *AddBalanceResponse) XXX_Size() int {
	return xxx_messageInfo_AddBalanceResponse.Size(m)
}
func (m *AddBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddBalanceResponse proto.InternalMessageInfo

func (m *AddBalanceResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type GetBalanceRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBalanceRequest) Reset()         { *m = GetBalanceRequest{} }
func (m *GetBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*GetBalanceRequest) ProtoMessage()    {}
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *GetBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalanceRequest.Unmarshal(m, b)
}
func (m *GetBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalanceRequest.Marshal(b, m, deterministic)
}
func (m *GetBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalanceRequest.Merge(m, src)
}
func (m *GetBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_GetBalanceRequest.Size(m)
}
func (m *GetBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalanceRequest proto.InternalMessageInfo

func (m *GetBalanceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetBalanceResponse struct {
	Balance              *Balance `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBalanceResponse) Reset()         { *m = GetBalanceResponse{} }
func (m *GetBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*GetBalanceResponse) ProtoMessage()    {}
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *GetBalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalanceResponse.Unmarshal(m, b)
}
func (m *GetBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalanceResponse.Marshal(b, m, deterministic)
}
func (m *GetBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalanceResponse.Merge(m, src)
}
func (m *GetBalanceResponse) XXX_Size() int {
	return xxx_messageInfo_GetBalanceResponse.Size(m)
}
func (m *GetBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalanceResponse proto.InternalMessageInfo

func (m *GetBalanceResponse) GetBalance() *Balance {
	if m != nil {
		return m.Balance
	}
	return nil
}

type ListBalanceRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBalanceRequest) Reset()         { *m = ListBalanceRequest{} }
func (m *ListBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*ListBalanceRequest) ProtoMessage()    {}
func (*ListBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *ListBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBalanceRequest.Unmarshal(m, b)
}
func (m *ListBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBalanceRequest.Marshal(b, m, deterministic)
}
func (m *ListBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBalanceRequest.Merge(m, src)
}
func (m *ListBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_ListBalanceRequest.Size(m)
}
func (m *ListBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBalanceRequest proto.InternalMessageInfo

type ListBalanceResponse struct {
	Balance              []*Balance `protobuf:"bytes,1,rep,name=balance,proto3" json:"balance,omitempty"`
	Total                int32      `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListBalanceResponse) Reset()         { *m = ListBalanceResponse{} }
func (m *ListBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*ListBalanceResponse) ProtoMessage()    {}
func (*ListBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *ListBalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBalanceResponse.Unmarshal(m, b)
}
func (m *ListBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBalanceResponse.Marshal(b, m, deterministic)
}
func (m *ListBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBalanceResponse.Merge(m, src)
}
func (m *ListBalanceResponse) XXX_Size() int {
	return xxx_messageInfo_ListBalanceResponse.Size(m)
}
func (m *ListBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBalanceResponse proto.InternalMessageInfo

func (m *ListBalanceResponse) GetBalance() []*Balance {
	if m != nil {
		return m.Balance
	}
	return nil
}

func (m *ListBalanceResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type PodInfo struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PodInfo) Reset()         { *m = PodInfo{} }
func (m *PodInfo) String() string { return proto.CompactTextString(m) }
func (*PodInfo) ProtoMessage()    {}
func (*PodInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *PodInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodInfo.Unmarshal(m, b)
}
func (m *PodInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodInfo.Marshal(b, m, deterministic)
}
func (m *PodInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodInfo.Merge(m, src)
}
func (m *PodInfo) XXX_Size() int {
	return xxx_messageInfo_PodInfo.Size(m)
}
func (m *PodInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PodInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PodInfo proto.InternalMessageInfo

func (m *PodInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type PodInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PodInfoRequest) Reset()         { *m = PodInfoRequest{} }
func (m *PodInfoRequest) String() string { return proto.CompactTextString(m) }
func (*PodInfoRequest) ProtoMessage()    {}
func (*PodInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}

func (m *PodInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodInfoRequest.Unmarshal(m, b)
}
func (m *PodInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodInfoRequest.Marshal(b, m, deterministic)
}
func (m *PodInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodInfoRequest.Merge(m, src)
}
func (m *PodInfoRequest) XXX_Size() int {
	return xxx_messageInfo_PodInfoRequest.Size(m)
}
func (m *PodInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PodInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PodInfoRequest proto.InternalMessageInfo

type PodInfoResponse struct {
	PodInfo              *PodInfo `protobuf:"bytes,1,opt,name=podInfo,proto3" json:"podInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PodInfoResponse) Reset()         { *m = PodInfoResponse{} }
func (m *PodInfoResponse) String() string { return proto.CompactTextString(m) }
func (*PodInfoResponse) ProtoMessage()    {}
func (*PodInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9}
}

func (m *PodInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodInfoResponse.Unmarshal(m, b)
}
func (m *PodInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodInfoResponse.Marshal(b, m, deterministic)
}
func (m *PodInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodInfoResponse.Merge(m, src)
}
func (m *PodInfoResponse) XXX_Size() int {
	return xxx_messageInfo_PodInfoResponse.Size(m)
}
func (m *PodInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PodInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PodInfoResponse proto.InternalMessageInfo

func (m *PodInfoResponse) GetPodInfo() *PodInfo {
	if m != nil {
		return m.PodInfo
	}
	return nil
}

type HealthCheckRequest struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckRequest) Reset()         { *m = HealthCheckRequest{} }
func (m *HealthCheckRequest) String() string { return proto.CompactTextString(m) }
func (*HealthCheckRequest) ProtoMessage()    {}
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{10}
}

func (m *HealthCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckRequest.Unmarshal(m, b)
}
func (m *HealthCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckRequest.Marshal(b, m, deterministic)
}
func (m *HealthCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckRequest.Merge(m, src)
}
func (m *HealthCheckRequest) XXX_Size() int {
	return xxx_messageInfo_HealthCheckRequest.Size(m)
}
func (m *HealthCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckRequest proto.InternalMessageInfo

func (m *HealthCheckRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

type HealthCheckResponse struct {
	Status               HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=balance.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *HealthCheckResponse) Reset()         { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()    {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{11}
}

func (m *HealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckResponse.Unmarshal(m, b)
}
func (m *HealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckResponse.Marshal(b, m, deterministic)
}
func (m *HealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckResponse.Merge(m, src)
}
func (m *HealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_HealthCheckResponse.Size(m)
}
func (m *HealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckResponse proto.InternalMessageInfo

func (m *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if m != nil {
		return m.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func init() {
	proto.RegisterEnum("balance.HealthCheckResponse_ServingStatus", HealthCheckResponse_ServingStatus_name, HealthCheckResponse_ServingStatus_value)
	proto.RegisterType((*Balance)(nil), "balance.Balance")
	proto.RegisterType((*AddBalanceRequest)(nil), "balance.AddBalanceRequest")
	proto.RegisterType((*AddBalanceResponse)(nil), "balance.AddBalanceResponse")
	proto.RegisterType((*GetBalanceRequest)(nil), "balance.GetBalanceRequest")
	proto.RegisterType((*GetBalanceResponse)(nil), "balance.GetBalanceResponse")
	proto.RegisterType((*ListBalanceRequest)(nil), "balance.ListBalanceRequest")
	proto.RegisterType((*ListBalanceResponse)(nil), "balance.ListBalanceResponse")
	proto.RegisterType((*PodInfo)(nil), "balance.PodInfo")
	proto.RegisterType((*PodInfoRequest)(nil), "balance.PodInfoRequest")
	proto.RegisterType((*PodInfoResponse)(nil), "balance.PodInfoResponse")
	proto.RegisterType((*HealthCheckRequest)(nil), "balance.HealthCheckRequest")
	proto.RegisterType((*HealthCheckResponse)(nil), "balance.HealthCheckResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 547 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x5d, 0x8f, 0xd2, 0x40,
	0x14, 0xa5, 0x60, 0xa9, 0xde, 0xba, 0xc0, 0x5e, 0x36, 0x5a, 0x59, 0x13, 0xc9, 0xf8, 0x42, 0x36,
	0xa6, 0x6b, 0xf0, 0x79, 0xa3, 0xcb, 0xba, 0xc1, 0x55, 0x03, 0xa6, 0xac, 0xf2, 0x48, 0x4a, 0x3b,
	0x0b, 0x8d, 0xd0, 0xa9, 0xcc, 0xe0, 0x0f, 0xf1, 0x67, 0x18, 0x5f, 0xfc, 0x87, 0x86, 0xe9, 0x0c,
	0x14, 0xda, 0x98, 0x18, 0x1f, 0xcf, 0xbd, 0x67, 0xce, 0x3d, 0xf7, 0xa3, 0x85, 0x23, 0x4e, 0x57,
	0xdf, 0xa3, 0x80, 0xba, 0xc9, 0x8a, 0x09, 0x86, 0xd6, 0xd4, 0x5f, 0xf8, 0x71, 0x40, 0x5b, 0xcf,
	0x66, 0x8c, 0xcd, 0x16, 0xf4, 0x5c, 0x86, 0xa7, 0xeb, 0xbb, 0x73, 0x11, 0x2d, 0x29, 0x17, 0xfe,
	0x32, 0x49, 0x99, 0xe4, 0x97, 0x01, 0x56, 0x2f, 0x25, 0x63, 0x0d, 0xca, 0x51, 0xe8, 0x18, 0x6d,
	0xa3, 0xf3, 0xc0, 0x2b, 0x47, 0x21, 0x3a, 0x60, 0xf9, 0x41, 0xc0, 0xd6, 0xb1, 0x70, 0xca, 0x32,
	0xa8, 0x21, 0x3e, 0x82, 0xaa, 0xbf, 0x94, 0x89, 0x4a, 0xdb, 0xe8, 0x98, 0x9e, 0x42, 0x78, 0x01,
	0x0f, 0x43, 0x5f, 0xd0, 0x89, 0x2a, 0xef, 0xdc, 0x6b, 0x1b, 0x1d, 0xbb, 0xdb, 0x72, 0x53, 0x17,
	0xae, 0x76, 0xe1, 0xde, 0x6a, 0x17, 0x9e, 0xbd, 0xe1, 0x6b, 0x03, 0x6d, 0xb0, 0x43, 0xca, 0x83,
	0x55, 0x94, 0x88, 0x88, 0xc5, 0x8e, 0x29, 0x8b, 0x66, 0x43, 0xe4, 0x35, 0x1c, 0x5f, 0x86, 0xa1,
	0xe2, 0x7b, 0xf4, 0xdb, 0x9a, 0x72, 0x81, 0x67, 0xa0, 0xfb, 0x95, 0xe6, 0xed, 0x6e, 0xc3, 0x55,
	0xd8, 0xd5, 0x4c, 0x4d, 0x20, 0x2f, 0x00, 0xb3, 0x02, 0x3c, 0x61, 0x31, 0xa7, 0x9b, 0x7e, 0x56,
	0x94, 0xaf, 0x17, 0x42, 0x0a, 0xdc, 0xf7, 0x14, 0x22, 0xcf, 0xe1, 0xb8, 0x4f, 0xc5, 0x41, 0xb9,
	0x83, 0x31, 0x91, 0x37, 0x80, 0x59, 0x92, 0x92, 0xfc, 0x17, 0x53, 0x27, 0x80, 0x1f, 0x23, 0x7e,
	0x50, 0x87, 0x8c, 0xa1, 0xb9, 0x17, 0x2d, 0x12, 0xae, 0xfc, 0x55, 0x18, 0x4f, 0xc0, 0x14, 0x4c,
	0xf8, 0x0b, 0xb9, 0x3f, 0xd3, 0x4b, 0x01, 0x79, 0x02, 0xd6, 0x27, 0x16, 0xde, 0xc4, 0x77, 0x4c,
	0xf6, 0x92, 0x6c, 0x7b, 0x49, 0x48, 0x03, 0x6a, 0x2a, 0xa5, 0x5d, 0x5c, 0x40, 0x7d, 0x1b, 0xd9,
	0x39, 0x48, 0xd2, 0x50, 0xae, 0x35, 0x4d, 0xd5, 0x04, 0xe2, 0x02, 0xbe, 0xa3, 0xfe, 0x42, 0xcc,
	0xaf, 0xe6, 0x34, 0xf8, 0xaa, 0x47, 0xe8, 0x80, 0xa5, 0x0e, 0x56, 0xd5, 0xd6, 0x90, 0xfc, 0x34,
	0xa0, 0xb9, 0xf7, 0x40, 0xd5, 0xec, 0x41, 0x95, 0x0b, 0x5f, 0xac, 0xb9, 0x7c, 0x50, 0xeb, 0x9e,
	0x6d, 0x4b, 0x16, 0xb0, 0xdd, 0xd1, 0x46, 0x2d, 0x9e, 0x8d, 0xe4, 0x0b, 0x4f, 0xbd, 0x24, 0x43,
	0x38, 0xda, 0x4b, 0xa0, 0x0d, 0xd6, 0xe7, 0xc1, 0x87, 0xc1, 0x70, 0x3c, 0x68, 0x94, 0x36, 0x60,
	0x74, 0xed, 0x7d, 0xb9, 0x19, 0xf4, 0x1b, 0x06, 0xd6, 0xc1, 0x1e, 0x0c, 0x6f, 0x27, 0x3a, 0x50,
	0xc6, 0x26, 0xd4, 0x25, 0xb8, 0xba, 0x9e, 0xe8, 0x27, 0x95, 0xee, 0xef, 0x32, 0xd4, 0xd4, 0xcc,
	0x47, 0xa9, 0x7f, 0x7c, 0x0f, 0x76, 0x66, 0x69, 0x78, 0xba, 0xb5, 0x99, 0x5f, 0x70, 0xeb, 0x69,
	0x71, 0x32, 0xed, 0x81, 0x94, 0xb0, 0x0f, 0xb0, 0x3b, 0x2c, 0x6c, 0x6d, 0xd9, 0xb9, 0x93, 0x6c,
	0x9d, 0x16, 0xe6, 0xb2, 0x42, 0xbb, 0xa3, 0xcf, 0x08, 0xe5, 0x3e, 0xa5, 0x8c, 0x50, 0xfe, 0x2b,
	0x21, 0x25, 0xbc, 0x94, 0x8e, 0xf4, 0xf1, 0x3c, 0xce, 0xad, 0x5d, 0xa9, 0x38, 0xf9, 0x84, 0x96,
	0xe8, 0xfe, 0x30, 0xa0, 0x9a, 0xae, 0x0c, 0x7b, 0x60, 0xca, 0xb5, 0x65, 0xa6, 0x94, 0xbf, 0x95,
	0xcc, 0x94, 0x8a, 0xee, 0xe2, 0x2d, 0x98, 0x63, 0x5f, 0x04, 0xf3, 0xff, 0xd0, 0x78, 0x69, 0x4c,
	0xab, 0xf2, 0xcf, 0xf4, 0xea, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x6f, 0x78, 0x4b, 0x47,
	0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BalanceServiceClient is the client API for BalanceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BalanceServiceClient interface {
	ListBalance(ctx context.Context, in *ListBalanceRequest, opts ...grpc.CallOption) (*ListBalanceResponse, error)
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
	AddBalance(ctx context.Context, in *AddBalanceRequest, opts ...grpc.CallOption) (*AddBalanceResponse, error)
	GetPodInfo(ctx context.Context, in *PodInfoRequest, opts ...grpc.CallOption) (*PodInfoResponse, error)
}

type balanceServiceClient struct {
	cc *grpc.ClientConn
}

func NewBalanceServiceClient(cc *grpc.ClientConn) BalanceServiceClient {
	return &balanceServiceClient{cc}
}

func (c *balanceServiceClient) ListBalance(ctx context.Context, in *ListBalanceRequest, opts ...grpc.CallOption) (*ListBalanceResponse, error) {
	out := new(ListBalanceResponse)
	err := c.cc.Invoke(ctx, "/balance.BalanceService/ListBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceServiceClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, "/balance.BalanceService/GetBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceServiceClient) AddBalance(ctx context.Context, in *AddBalanceRequest, opts ...grpc.CallOption) (*AddBalanceResponse, error) {
	out := new(AddBalanceResponse)
	err := c.cc.Invoke(ctx, "/balance.BalanceService/AddBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceServiceClient) GetPodInfo(ctx context.Context, in *PodInfoRequest, opts ...grpc.CallOption) (*PodInfoResponse, error) {
	out := new(PodInfoResponse)
	err := c.cc.Invoke(ctx, "/balance.BalanceService/GetPodInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BalanceServiceServer is the server API for BalanceService service.
type BalanceServiceServer interface {
	ListBalance(context.Context, *ListBalanceRequest) (*ListBalanceResponse, error)
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
	AddBalance(context.Context, *AddBalanceRequest) (*AddBalanceResponse, error)
	GetPodInfo(context.Context, *PodInfoRequest) (*PodInfoResponse, error)
}

// UnimplementedBalanceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBalanceServiceServer struct {
}

func (*UnimplementedBalanceServiceServer) ListBalance(ctx context.Context, req *ListBalanceRequest) (*ListBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBalance not implemented")
}
func (*UnimplementedBalanceServiceServer) GetBalance(ctx context.Context, req *GetBalanceRequest) (*GetBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalance not implemented")
}
func (*UnimplementedBalanceServiceServer) AddBalance(ctx context.Context, req *AddBalanceRequest) (*AddBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBalance not implemented")
}
func (*UnimplementedBalanceServiceServer) GetPodInfo(ctx context.Context, req *PodInfoRequest) (*PodInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPodInfo not implemented")
}

func RegisterBalanceServiceServer(s *grpc.Server, srv BalanceServiceServer) {
	s.RegisterService(&_BalanceService_serviceDesc, srv)
}

func _BalanceService_ListBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceServiceServer).ListBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/balance.BalanceService/ListBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceServiceServer).ListBalance(ctx, req.(*ListBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalanceService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/balance.BalanceService/GetBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceServiceServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalanceService_AddBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceServiceServer).AddBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/balance.BalanceService/AddBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceServiceServer).AddBalance(ctx, req.(*AddBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalanceService_GetPodInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PodInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceServiceServer).GetPodInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/balance.BalanceService/GetPodInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceServiceServer).GetPodInfo(ctx, req.(*PodInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BalanceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "balance.BalanceService",
	HandlerType: (*BalanceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBalance",
			Handler:    _BalanceService_ListBalance_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _BalanceService_GetBalance_Handler,
		},
		{
			MethodName: "AddBalance",
			Handler:    _BalanceService_AddBalance_Handler,
		},
		{
			MethodName: "GetPodInfo",
			Handler:    _BalanceService_GetPodInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

// HealthClient is the client API for Health service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HealthClient interface {
	Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	Watch(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (Health_WatchClient, error)
}

type healthClient struct {
	cc *grpc.ClientConn
}

func NewHealthClient(cc *grpc.ClientConn) HealthClient {
	return &healthClient{cc}
}

func (c *healthClient) Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/balance.Health/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthClient) Watch(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (Health_WatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Health_serviceDesc.Streams[0], "/balance.Health/Watch", opts...)
	if err != nil {
		return nil, err
	}
	x := &healthWatchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Health_WatchClient interface {
	Recv() (*HealthCheckResponse, error)
	grpc.ClientStream
}

type healthWatchClient struct {
	grpc.ClientStream
}

func (x *healthWatchClient) Recv() (*HealthCheckResponse, error) {
	m := new(HealthCheckResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HealthServer is the server API for Health service.
type HealthServer interface {
	Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	Watch(*HealthCheckRequest, Health_WatchServer) error
}

// UnimplementedHealthServer can be embedded to have forward compatible implementations.
type UnimplementedHealthServer struct {
}

func (*UnimplementedHealthServer) Check(ctx context.Context, req *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (*UnimplementedHealthServer) Watch(req *HealthCheckRequest, srv Health_WatchServer) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}

func RegisterHealthServer(s *grpc.Server, srv HealthServer) {
	s.RegisterService(&_Health_serviceDesc, srv)
}

func _Health_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/balance.Health/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServer).Check(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Health_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HealthCheckRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HealthServer).Watch(m, &healthWatchServer{stream})
}

type Health_WatchServer interface {
	Send(*HealthCheckResponse) error
	grpc.ServerStream
}

type healthWatchServer struct {
	grpc.ServerStream
}

func (x *healthWatchServer) Send(m *HealthCheckResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Health_serviceDesc = grpc.ServiceDesc{
	ServiceName: "balance.Health",
	HandlerType: (*HealthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _Health_Check_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _Health_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service.proto",
}
